apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cms-shared-pvc
spec:
  accessModes:
  - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 500Gi
  volumeName: shared
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dbdata-pvc
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: ""
  resources:
    requests:
      storage: 10Gi
  volumeName: dbdata
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      volumes:
      - name: dbdata
        persistentVolumeClaim:
          claimName: dbdata-pvc
      initContainers:
      - name: pgsql-data-permission-fix
        image: busybox:1.26.2
        command: ["/bin/chown","-R","1001", "/bitnami/postgresql"]
        volumeMounts:
        - name: dbdata
          mountPath: /bitnami/postgresql
      containers:
      - name: postgres
        image: bitnami/postgresql:10
        imagePullPolicy: Always
        ports:
        - containerPort: 5432
          protocol: TCP
        env:
        - name: POSTGRESQL_USERNAME
          value: dotcmsdbuser 
        - name: POSTGRESQL_PASSWORD
          value: password 
        - name: POSTGRESQL_DATABASE
          value: dotcms
        - name: BITNAMI_DEBUG
          value: "true"
        volumeMounts:
        - name: dbdata
          mountPath: /bitnami/postgresql
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: db-svc
spec:
  ports:
  - port: 5432
  selector:
    app: postgres
  type: ClusterIP
---

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: dotcms
spec:
  replicas: 3
  selector:
    matchLabels:
      app: dotcms
  template:
    metadata:
      labels:
        app: dotcms
    spec:
      volumes:
      - name: cmsshared
        persistentVolumeClaim:
          claimName: cms-shared-pvc
      - name: licensefile
        configMap:
          name: dotcmslicensepack
      initContainers:
      - name: cmsshared-permission-fix
        image: busybox:1.26.2
        command:
          - sh
          - -c
          - mkdir -p /data/shared/assets && cp /license.zip /data/shared/assets/.  && chown -R 1000000000 /data/shared
        volumeMounts:
        - name: cmsshared
          mountPath: /data/shared
        - name: licensefile
          mountPath: "/license.zip"
          subPath: "license.zip"
      containers:
      - name: dotcms
        image: dotcms/dotcms:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8081
          protocol: TCP
        - containerPort: 8082
          protocol: TCP
        env:
        - name: CMS_HEAP_SIZE
          value: 2G
        - name: CMS_JAVA_OPTS
          value: -XX:+PrintFlagsFinal
        - name: PROVIDER_DB_DNSNAME
          value: db-svc
        - name: PROVIDER_ELASTICSEARCH_DNSNAMES
          value: elasticsearch-svc
        - name: PROVIDER_ELASTICSEARCH_SVC_DELAY_MAX
          value: "60"
        - name: PREVENT_SESSION_FIXATION_ON_LOGIN
          value: "false"
        volumeMounts:
        - name: cmsshared
          mountPath: /data/shared
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: dotcms
spec:
  ports:
  - name: dotcms-http
    port: 8081
    protocol: TCP
  - name: dotcms-https
    port: 8082
    protocol: TCP
  selector:
    app: dotcms
  type: ClusterIP
  
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: haproxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: haproxy 
  template:
    metadata:
      name: haproxy
      labels:
        app: haproxy
    spec:
      containers:
      - name: haproxy
        image: dotcms/haproxy:1.8-os
        imagePullPolicy: Always
        ports:
          - containerPort: 8080
          - containerPort: 8443
---
apiVersion: v1
kind: Service
metadata:
  name: haproxy-svc
spec:
  selector:
    app: haproxy
  ports:
  - name: http
    port: 80
    targetPort: 8080
  - name: https
    port: 443
    targetPort: 8443
  type: LoadBalancer
  externalTrafficPolicy: Local
  sessionAffinity: None