apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cms-shared-pvc
spec:
  accessModes:
  - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 1000Gi
  volumeName: shared
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dbdata-pvc
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: ""
  resources:
    requests:
      storage: 10Gi
  volumeName: dbdata
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: es-static-pvc
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: ""
  resources:
    requests:
      storage: 10Gi
  volumeName: esstatic
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      volumes:
      - name: dbdata
        persistentVolumeClaim:
          claimName: dbdata-pvc
      initContainers:
      - name: pgsql-data-permission-fix
        image: busybox:1.26.2
        command: ["/bin/chown","-R","1001", "/bitnami/postgresql"]
        volumeMounts:
        - name: dbdata
          mountPath: /bitnami/postgresql
      containers:
      - name: postgres
        image: bitnami/postgresql:10
        imagePullPolicy: Always
        ports:
        - containerPort: 5432
          protocol: TCP
        env:
        - name: POSTGRESQL_USERNAME
          value: dotcmsdbuser 
        - name: POSTGRESQL_PASSWORD
          value: password 
        - name: POSTGRESQL_DATABASE
          value: dotcms
        - name: BITNAMI_DEBUG
          value: "true"
        volumeMounts:
        - name: dbdata
          mountPath: /bitnami/postgresql
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: db-svc
spec:
  ports:
  - port: 5432
  selector:
    app: postgres
  type: ClusterIP
---



apiVersion: apps/v1
kind: Deployment
metadata:
  name: elasticsearch-static
spec:
  replicas: 1
  selector:
    matchLabels:
      app: elasticsearch-static
      apptype: elasticsearch
      appversion: 6.1.3
  template:
    metadata:
      labels:
        app: elasticsearch-static
        apptype: elasticsearch
        appversion: 6.1.3
    spec:
      volumes:
      - name: esstaticstorage
        persistentVolumeClaim:
          claimName: es-static-pvc
      initContainers:
      - name: esdata-permission-fix
        image: busybox:1.26.2
        command: ["/bin/chown","-R","10001", "/data"]
        volumeMounts:
        - name: esstaticstorage
          mountPath: /data
      containers:
      - name: esstatic
        image: dotcms/elasticsearch:6.1.3-os
        imagePullPolicy: Always
        ports:
        - name: http
          containerPort: 9200
          protocol: TCP
        - name: transport
          containerPort: 9300
          protocol: TCP
        env:
        - name: PROVIDER_ELASTICSEARCH_HEAP_SIZE
          value: 1500m
        - name: PROVIDER_ELASTICSEARCH_DNSNAMES
          value: elasticsearch-svc
        - name: PROVIDER_ELASTICSEARCH_SVC_DELAY_MIN
          value: "1"
        - name: PROVIDER_ELASTICSEARCH_SVC_DELAY_STEP
          value: "1"
        - name: PROVIDER_ELASTICSEARCH_SVC_DELAY_MAX
          value: "2"
        - name: PROVIDER_ELASTICSEARCH_ADDR_TRANSPORT
          value: "0.0.0.0"
        volumeMounts:
        - name: esstaticstorage
          mountPath: /data
      restartPolicy: Always
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: elasticsearch
spec:
  replicas: 1
  selector:
    matchLabels:
      app: elasticsearch
      apptype: elasticsearch
      appversion: 6.1.3
  template:
    metadata:
      labels:
        app: elasticsearch
        apptype: elasticsearch
        appversion: 6.1.3
    spec:
      containers:
      - name: es
        image: dotcms/elasticsearch:6.1.3-os
        imagePullPolicy: Always
        ports:
        - name: http
          containerPort: 9200
          protocol: TCP
        - name: transport
          containerPort: 9300
          protocol: TCP
        env:
        - name: PROVIDER_ELASTICSEARCH_HEAP_SIZE
          value: 1500m
        - name: PROVIDER_ELASTICSEARCH_DNSNAMES
          value: elasticsearch-svc
        - name: PROVIDER_ELASTICSEARCH_SVC_DELAY_MIN
          value: "5"
        - name: PROVIDER_ELASTICSEARCH_SVC_DELAY_STEP
          value: "1"
        - name: PROVIDER_ELASTICSEARCH_SVC_DELAY_MAX
          value: "15"
        - name: PROVIDER_ELASTICSEARCH_ADDR_TRANSPORT
          value: "0.0.0.0"
        - name: PROVIDER_ELASTICSEARCH_NODE_MASTER
          value: "false"
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
    name: elasticsearch-svc
spec:
  ports:
  - name: http
    port: 9200
  - name: transport
    port: 9300
  selector:
    apptype: elasticsearch
    appversion: 6.1.3
    
  clusterIP: None
  
  
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: dotcms
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dotcms
  template:
    metadata:
      labels:
        app: dotcms
    spec:
      volumes:
      - name: cmsshared
        persistentVolumeClaim:
          claimName: cms-shared-pvc
      - name: licensefile
        configMap:
          name: dotcmslicensepack
      initContainers:
      - name: cmsshared-permission-fix
        image: busybox:1.26.2
        command:
          - sh
          - -c
          - mkdir -p /data/shared/assets && cp /license.zip /data/shared/assets/.  && chown -R 1000000000 /data/shared
        volumeMounts:
        - name: cmsshared
          mountPath: /data/shared
        - name: licensefile
          mountPath: "/license.zip"
          subPath: "license.zip"
      containers:
      - name: dotcms
        image: dotcms/dotcms:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8081
          protocol: TCP
        - containerPort: 8082
          protocol: TCP
        env:
        - name: CMS_HEAP_SIZE
          value: 2G
        - name: CMS_JAVA_OPTS
          value: -XX:+PrintFlagsFinal
        - name: PROVIDER_DB_DNSNAME
          value: db-svc
        - name: PROVIDER_ELASTICSEARCH_DNSNAMES
          value: elasticsearch-svc
        - name: PROVIDER_ELASTICSEARCH_SVC_DELAY_MAX
          value: "60"
        volumeMounts:
        - name: cmsshared
          mountPath: /data/shared
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: dotcms
spec:
  ports:
  - name: dotcms-http
    port: 8081
    protocol: TCP
  - name: dotcms-https
    port: 8082
    protocol: TCP
  selector:
    app: dotcms
  type: ClusterIP
  
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: haproxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: haproxy 
  template:
    metadata:
      name: haproxy
      labels:
        app: haproxy
    spec:
      containers:
      - name: haproxy
        image: dotcms/haproxy:1.8-os
        imagePullPolicy: Always
        ports:
          - containerPort: 8080
          - containerPort: 8443
---
apiVersion: v1
kind: Service
metadata:
  name: haproxy-svc
spec:
  selector:
    app: haproxy
  ports:
  - name: http
    port: 80
    targetPort: 8080
  - name: https
    port: 443
    targetPort: 8443
  type: LoadBalancer
  externalTrafficPolicy: Local
  sessionAffinity: None