apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      volumes:
      - name: dbdata
        persistentVolumeClaim:
          claimName: dbdata-pvc
      containers:
      - name: postgres
        image: postgres:11
        command: ["docker-entrypoint.sh"]
        args: ["-c", "max_connections=200", "-c", "shared_buffers=80MB"]
        imagePullPolicy: Always
        ports:
        - containerPort: 5432
          protocol: TCP
        env:
        - name: POSTGRES_USER
          value: dotcmsdbuser 
        - name: POSTGRES_PASSWORD
          value: password 
        - name: POSTGRES_DB
          value: dotcms
        - name: PGDATA
          value: /postgres/data
        volumeMounts:
        - name: dbdata
          mountPath: /postgres
      restartPolicy: Always

