apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cms-shared-pvc
spec:
  accessModes:
  - ReadWriteMany
  storageClassName: "nfs"
  resources:
    requests:
      storage: 100Gi
  volumeName: shared