apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfsdata-pvc
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: ""
  resources:
    requests:
      storage: 100Gi
  volumeName: nfsdata
