
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dbdata-pvc
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
---


apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      volumes:
      - name: dbdata
        persistentVolumeClaim:
          claimName: dbdata-pvc
      containers:
      - name: postgres
        image: postgres:11
        imagePullPolicy: Always
        command:
          - "docker-entrypoint.sh"
          - "-c"
          - "max_connections=1000"
          - "-c"
          - "shared_buffers=3GB"
        ports:
        - containerPort: 5432
          protocol: TCP
        env:
        - name: POSTGRES_USER
          value: dotcmsdbuser 
        - name: POSTGRES_PASSWORD
          value: password 
        - name: POSTGRES_DB
          value: dotcms
        - name: PGDATA
          value: /postgres/data
        volumeMounts:
        - name: dbdata
          mountPath: /postgres
      restartPolicy: Always

---
apiVersion: v1
kind: Service
metadata:
  name: postgres
spec:
  ports:
  - port: 5432
  selector:
    app: postgres
  type: ClusterIP