apiVersion: v1
kind: PersistentVolume
metadata:
  name: esdata
spec:
  capacity:
    storage: 100Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  gcePersistentDisk:
    fsType: ext4
    readOnly: false
    pdName: esdata 

  