apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: elasticsearch
spec:
  serviceName : "elasticsearch"
  replicas: 3
  selector:
    matchLabels:
      app: elasticsearch
  template:
    metadata:
      labels:
        app: elasticsearch
    spec:
      containers:
      - name: elasticsearch
        image: gcr.io/cicd-246518/es-open-distro:1.3.0
        imagePullPolicy: Always
        ports:
        - name: http
          containerPort: 9200
          protocol: TCP
        - name: transport
          containerPort: 9300
          protocol: TCP
        env:
        - name: PROVIDER_ELASTICSEARCH_HEAP_SIZE
          value: 1500m
        - name: PROVIDER_ELASTICSEARCH_DNSNAMES
          value: elasticsearch-svc
        - name: PROVIDER_ELASTICSEARCH_SVC_DELAY_MIN
          value: "1"
        - name: PROVIDER_ELASTICSEARCH_SVC_DELAY_STEP
          value: "1"
        - name: PROVIDER_ELASTICSEARCH_SVC_DELAY_MAX
          value: "2"
        - name: PROVIDER_ELASTICSEARCH_ADDR_TRANSPORT
          value: "0.0.0.0"
        - name: "ES_ADMIN_PASSWORD"
          value: "admin"
        volumeMounts:
        - name: elasticsearch-vol
          mountPath: /data
      initContainers:
      - name: init-sysctl
        image: busybox:1.27.2
        command:
        - sysctl
        - -w
        - vm.max_map_count=262144
        securityContext:
          privileged: true
      - name: esdata-permission-fix
        image: busybox:1.26.2
        command: ["/bin/chown","-R","10001", "/data"]
        volumeMounts:
        - name: elasticsearch-vol
          mountPath: /data
      restartPolicy: Always
  volumeClaimTemplates:
  - metadata:
      name: elasticsearch-vol
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "standard"
      resources:
        requests:
          storage: 50Gi
