---
## https://opendistro.github.io/for-elasticsearch-docs/docs/install/helm/


apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  labels:
    app: opendistro-es
    chart: "opendistro-es-1.6.0"
    release: "opendistro-es"
    heritage: "Helm"
  name: opendistro-es-psp
spec:
  privileged: true
  #requiredDropCapabilities:
  volumes:
    - 'configMap'
    - 'emptyDir'
    - 'projected'
    - 'secret'
    - 'downwardAPI'
    - 'persistentVolumeClaim'
  hostNetwork: false
  hostIPC: false
  hostPID: false
  runAsUser:
    rule: 'RunAsAny'
  seLinux:
    rule: 'RunAsAny'
  supplementalGroups:
    rule: 'MustRunAs'
    ranges:
      - min: 1
        max: 65535
  fsGroup:
    rule: 'MustRunAs'
    ranges:
      - min: 1
        max: 65535
  readOnlyRootFilesystem: false
---



apiVersion: v1
kind: ServiceAccount
metadata:
  name: opendistro-es-es
  namespace: default
  labels:
    app: opendistro-es
    chart: "opendistro-es-1.6.0"
    release: "opendistro-es"
    heritage: "Helm"
---



apiVersion: v1
kind: ServiceAccount
metadata:
  name: opendistro-es-kibana
  namespace: default
  labels:
    app: opendistro-es
    chart: "opendistro-es-1.6.0"
    release: "opendistro-es"
    heritage: "Helm"
---

apiVersion: v1
kind: Secret
metadata:
  name: opendistro-es-es-config
  namespace: default
  labels:
    app: opendistro-es
    chart: "opendistro-es-1.6.0"
    release: "opendistro-es"
    heritage: "Helm"
type: Opaque
data:
  logging.yml: "YXBwZW5kZXI6CiAgY29uc29sZToKICAgIGxheW91dDoKICAgICAgY29udmVyc2lvblBhdHRlcm46ICdbJWR7SVNPODYwMX1dWyUtNXBdWyUtMjVjXSAlbSVuJwogICAgICB0eXBlOiBjb25zb2xlUGF0dGVybgogICAgdHlwZTogY29uc29sZQplcy5sb2dnZXIubGV2ZWw6IElORk8KbG9nZ2VyOgogIGFjdGlvbjogREVCVUcKICBjb20uYW1hem9uYXdzOiBXQVJOCnJvb3RMb2dnZXI6ICR7ZXMubG9nZ2VyLmxldmVsfSwgY29uc29sZQ=="
---


apiVersion: rbac.authorization.k8s.io/v1beta1
kind: Role
metadata:
  name: opendistro-es-es
  namespace: default
  labels:
    app: opendistro-es
    chart: "opendistro-es-1.6.0"
    release: "opendistro-es"
    heritage: "Helm"
rules:
- apiGroups: ['extensions']
  resources: ['podsecuritypolicies']
  verbs:     ['use']
  resourceNames:
  - opendistro-es-psp
---


apiVersion: rbac.authorization.k8s.io/v1beta1
kind: Role
metadata:
  name: opendistro-es-kibana
  namespace: default
  labels:
    app: opendistro-es
    chart: "opendistro-es-1.6.0"
    release: "opendistro-es"
    heritage: "Helm"
rules:
- apiGroups: ['extensions']
  resources: ['podsecuritypolicies']
  verbs:     ['use']
  resourceNames:
  - opendistro-es-psp
---


kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  labels:
    app: opendistro-es
    chart: "opendistro-es-1.6.0"
    release: "opendistro-es"
    heritage: "Helm"
  name: opendistro-es-elastic-rolebinding
roleRef:
  kind: Role
  name: opendistro-es-es
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: opendistro-es-es
  namespace: default
---


kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  labels:
    app: opendistro-es
    chart: "opendistro-es-1.6.0"
    release: "opendistro-es"
    heritage: "Helm"
  name: opendistro-es-kibana-rolebinding
roleRef:
  kind: Role
  name: opendistro-es-kibana
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: opendistro-es-kibana
  namespace: default
---


apiVersion: v1
kind: Service
metadata:
  labels:
    app: opendistro-es
    chart: "opendistro-es-1.6.0"
    release: "opendistro-es"
    heritage: "Helm"
    role: data
  name: opendistro-es-data-svc
  namespace: default
spec:
  ports:
  - port: 9300
    name: transport
  - port: 9200
    name: http
  - port: 9600
    name: metrics
  clusterIP: None
  selector:
    role: data
---


kind: Service
apiVersion: v1
metadata:
  annotations:
    {}
  labels:
    app: opendistro-es
    chart: "opendistro-es-1.6.0"
    release: "opendistro-es"
    heritage: "Helm"
    role: client
  name: opendistro-es-client-service
  namespace: default
spec:
  ports:
    - name: http
      port: 9200
    - name: transport
      port: 9300
    - name: metrics
      port: 9600
  selector:
    role: client
  type: ClusterIP
---


apiVersion: v1
kind: Service
metadata:
  labels:
    app: opendistro-es
    chart: "opendistro-es-1.6.0"
    release: "opendistro-es"
    heritage: "Helm"
    role: master
  name: opendistro-es-discovery
  namespace: default
spec:
  ports:
    - port: 9300
      protocol: TCP
  clusterIP: None
  selector:
    role: master
---

apiVersion: v1
kind: Service
metadata:
  annotations:
    {}
  labels:
    app: opendistro-es
    chart: "opendistro-es-1.6.0"
    release: "opendistro-es"
    heritage: "Helm"
    role: kibana
  name: opendistro-es-kibana-svc
spec:
  ports:
  - name: kibana-svc
    port: 443
    targetPort: 5601
  selector:
    role: kibana
  type: ClusterIP
---


apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: opendistro-es
    chart: "opendistro-es-1.6.0"
    release: "opendistro-es"
    heritage: "Helm"
    role: client
  name: opendistro-es-client
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: opendistro-es
      release: "opendistro-es"
      heritage: "Helm"
      role: client
  template:
    metadata:
      labels:
        app: opendistro-es
        chart: "opendistro-es-1.6.0"
        release: "opendistro-es"
        heritage: "Helm"
        role: client
      annotations:
        
    spec:      
      serviceAccountName: opendistro-es-es
      initContainers:
      - name: init-sysctl
        image: busybox:1.27.2
        command:
        - sysctl
        - -w
        - vm.max_map_count=262144
        securityContext:
          privileged: true
      containers:
      - name: elasticsearch
        env:
        - name: cluster.name
          value: elasticsearch
        - name: node.master
          value: "false"
        - name: node.ingest
          value: "true"
        - name: node.data
          value: "false"
        - name: network.host
          value: "0.0.0.0"
        - name: node.name
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: discovery.seed_hosts
          value: opendistro-es-discovery
        - name: KUBERNETES_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: PROCESSORS
          valueFrom:
            resourceFieldRef:
              resource: limits.cpu
        - name: ES_JAVA_OPTS
          value: -Xms512m -Xmx512m
        resources:
            {}
        # Official Image from Open Distro Team
        image: amazon/opendistro-for-elasticsearch:1.6.0
        imagePullPolicy: "Always"
        ports:
        - containerPort: 9200
          name: http
        - containerPort: 9300
          name: transport
        - containerPort: 9600
          name: metrics
        livenessProbe:
          initialDelaySeconds: 60
          periodSeconds: 10
          tcpSocket:
            port: transport
        volumeMounts:
        - mountPath: /usr/share/elasticsearch/config/logging.yml
          name: config
          subPath: logging.yml
      volumes:
      - name: config
        secret:
          secretName: opendistro-es-es-config
---


apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: opendistro-es
    chart: "opendistro-es-1.6.0"
    release: "opendistro-es"
    heritage: "Helm"
    role: kibana
  name: opendistro-es-kibana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: opendistro-es
      release: "opendistro-es"
      heritage: "Helm"
      role: kibana
  template:
    metadata:
      labels:
        app: opendistro-es
        chart: "opendistro-es-1.6.0"
        release: "opendistro-es"
        heritage: "Helm"
        role: kibana
      annotations:
        
    spec:      
      containers:
      - env:
        - name: CLUSTER_NAME
          value: elasticsearch
        # If no custom configuration provided, default to internal DNS
        - name: ELASTICSEARCH_HOSTS
          value: https://opendistro-es-client-service:9200
        image: amazon/opendistro-for-elasticsearch-kibana:1.6.0
        resources:
            {}
        name: opendistro-es-kibana
        volumeMounts:
        ports:
        - containerPort: 5601
      serviceAccountName: opendistro-es-kibana
      volumes:
      restartPolicy: Always
---



apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: opendistro-es
    chart: "opendistro-es-1.6.0"
    release: "opendistro-es"
    heritage: "Helm"
    role: data
  name: opendistro-es-data
  namespace: default
spec:
  serviceName: opendistro-es-data-svc
  replicas: 1
  selector:
    matchLabels:
      app: opendistro-es
      release: "opendistro-es"
      heritage: "Helm"
      role: data
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: opendistro-es
        chart: "opendistro-es-1.6.0"
        release: "opendistro-es"
        heritage: "Helm"
        role: data
      annotations:
        
    spec:      
      initContainers:
      - name: init-sysctl
        image: busybox:1.27.2
        command:
        - sysctl
        - -w
        - vm.max_map_count=262144
        securityContext:
          privileged: true
      - name: fixmount
        command: [ 'sh', '-c', 'chown -R 1000:1000 /usr/share/elasticsearch/data' ]
        image: busybox:1.27.2
        volumeMounts:
          - mountPath: /usr/share/elasticsearch/data
            name: data
            subPath: 
      serviceAccountName: opendistro-es-es
      containers:
      - name: elasticsearch
        env:
        - name: cluster.name
          value: elasticsearch
        - name: node.master
          value: "false"
        - name: node.ingest
          value: "false"
        - name: network.host
          value: "0.0.0.0"
        - name: node.name
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: discovery.seed_hosts
          value: "opendistro-es-discovery"
        - name: KUBERNETES_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: node.data
          value: "true"
        - name: PROCESSORS
          valueFrom:
            resourceFieldRef:
              resource: limits.cpu
        - name: ES_JAVA_OPTS
          value: -Xms512m -Xmx512m
        # Official Image from Open Distro Team
        image: amazon/opendistro-for-elasticsearch:1.6.0
        imagePullPolicy: "Always"
        # only publish the transport port
        ports:
        - containerPort: 9300
          name: transport
        resources:
            {}
        livenessProbe:
          initialDelaySeconds: 60
          periodSeconds: 10
          tcpSocket:
            port: transport
        volumeMounts:
        - mountPath: /usr/share/elasticsearch/data
          name: data
          subPath: 
        - mountPath: /usr/share/elasticsearch/config/logging.yml
          name: config
          subPath: logging.yml
      volumes:
      - name: config
        secret:
          secretName: opendistro-es-es-config
  volumeClaimTemplates:
  - metadata:
      name: data
      annotations:
    spec:
      accessModes:
        - "ReadWriteOnce"
      resources:
        requests:
          storage: "8Gi"
---
# Source: opendistro-es/templates/elasticsearch/es-master-sts.yaml
# Copyright 2019 Viasat, Inc.
# Copyright 2019 Amazon.com, Inc. or its affiliates. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License").
# You may not use this file except in compliance with the License.
# A copy of the License is located at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# or in the "license" file accompanying this file. This file is distributed
# on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
# express or implied. See the License for the specific language governing
# permissions and limitations under the License.


apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: opendistro-es
    chart: "opendistro-es-1.6.0"
    release: "opendistro-es"
    heritage: "Helm"
    role: master
  name: opendistro-es-master
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: opendistro-es
      release: "opendistro-es"
      heritage: "Helm"
      role: master
  updateStrategy:
    type: RollingUpdate
  serviceName: opendistro-es-discovery
  template:
    metadata:
      labels:
        app: opendistro-es
        chart: "opendistro-es-1.6.0"
        release: "opendistro-es"
        heritage: "Helm"
        role: master
      annotations:
        
    spec:      
      serviceAccountName: opendistro-es-es
      initContainers:
      - name: init-sysctl
        image: busybox:1.27.2
        command:
        - sysctl
        - -w
        - vm.max_map_count=262144
        securityContext:
          privileged: true
      - name: fixmount
        command: [ 'sh', '-c', 'chown -R 1000:1000 /usr/share/elasticsearch/data' ]
        image: busybox:1.27.2
        volumeMounts:
          - mountPath: /usr/share/elasticsearch/data
            name: data
            subPath: 
      containers:
      - name: elasticsearch
        env:
        - name: cluster.name
          value: elasticsearch
        - name: cluster.initial_master_nodes
          value: opendistro-es-master-0,
        - name: node.master
          value: "true"
        - name: node.ingest
          value: "false"
        - name: node.data
          value: "false"
        - name: network.host
          value: "0.0.0.0"
        - name: node.name
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: discovery.seed_hosts
          value: opendistro-es-discovery
        - name: KUBERNETES_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: PROCESSORS
          valueFrom:
            resourceFieldRef:
              resource: limits.cpu
        - name: ES_JAVA_OPTS
          value: -Xms512m -Xmx512m
        resources:
            {}
        livenessProbe:
          initialDelaySeconds: 60
          periodSeconds: 10
          tcpSocket:
            port: transport
        # Official Image from Open Distro Team
        image: amazon/opendistro-for-elasticsearch:1.6.0
        imagePullPolicy: "Always"
        ports:
        - containerPort: 9300
          name: transport
        - containerPort: 9200
          name: http
        - containerPort: 9600
          name: metrics
        volumeMounts:
        - mountPath: /usr/share/elasticsearch/data
          name: data
          subPath: 
        - mountPath: /usr/share/elasticsearch/config/logging.yml
          name: config
          subPath: logging.yml
      volumes:
      - name: config
        secret:
          secretName: opendistro-es-es-config
  volumeClaimTemplates:
  - metadata:
      name: data
      annotations:
    spec:
      accessModes:
        - "ReadWriteOnce"
      resources:
        requests:
          storage: "8Gi"
---
