---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: haproxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: haproxy 
  template:
    metadata:
      name: haproxy
      labels:
        app: haproxy
    spec:
      containers:
      - name: haproxy
        image: dotcms/haproxy:1.8-os
        imagePullPolicy: Always
        ports:
          - containerPort: 8080
          - containerPort: 8443
---
apiVersion: v1
kind: Service
metadata:
  name: haproxy-svc
spec:
  selector:
    app: haproxy
  ports:
  - name: http
    port: 80
    targetPort: 8080
  - name: https
    port: 443
    targetPort: 8443
  type: LoadBalancer
  externalTrafficPolicy: Local
  sessionAffinity: None